GET localhost/api/user/1

###
POST localhost/api/signUp
Content-Type: application/json

{
  "firstName": "MyName",
  "lastName": "MyLastName",
  "middleName": "MyMiddleName",
  "password": "MyPassword"
}

###
GET localhost/api/user/all